server:
  port : 7000
spring:
  application:
    name: zuul
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuul-data-limit
    username: root
    password:
  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
zuul:
  routes:
    rate:
      path: /products/**
      url: http://localhost:7001/products
  ratelimit:
    enabled: true
    repository: JPA
    policy-list:
      rate:
        - limit: 1
          refresh-interval: 60
          type:
            - origin
  strip-prefix: true
